public class GenericAppConfiguration {
	public Double apiVersion { get; set; }
	public String baseUrl { get; set; }
	public String baseDevUrl { get; set; }
	public String waveApplicationsUrl { get; set; }
	public Integer objectLoadingBatchSize { get; set; }
	public Integer timeShiftingBatchSize { get; set; }
	public String faqJsonUrl { get; set; }
	public String homeHeaderDescription { get; set; }
	public String tplDeployBaseUrl { get; set; }
}