public class WaveApplicationObjectField {
	public String Label {get; set;}
	public String Name {get; set;}
	public String Type {get; set;}
	public String PickListValues {get; set;}
	public String ReferenceTo {get; set;}
	public Integer Length {get; set;}
	public Integer Precision {get; set;}
	public Integer Scale {get; set;}
	public Boolean IsExternalId {get; set;}
	public Boolean IsRequired {get; set;}
	public String DefaultValue {get; set;}
	public String Formula {get; set;}
}