public class WaveApplicationEdgemart {
    public String objectName { get; set; }
    public String edgemartDeveloperName { get; set; }
    public String edgemartLabel { get; set; }
    public String edgemartCsvDataUrl { get; set; }
    public String edgemartJsonSchemaUrl { get; set; }
    public String edgemartNodeNameInDataflow { get; set; }
    public String edgemartNodeNameToReplaceInDataflow { get; set; }
    public Boolean replaceData { get; set; }
}